# Generated by Django 4.1 on 2022-11-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_category_ja_product_category_zh_hans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_zh_hans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_zh_hans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_zh_hans',
        ),
    ]
