# Generated by Django 4.1 on 2022-11-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_category_zh_hans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_zh_hans',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категоря'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_zh_hans',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название Устройства'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_zh_hans',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание'),
        ),
    ]
