# Generated by Django 4.1 on 2022-11-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='order',
            name='city_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='city_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
