# Generated by Django 4.1 on 2022-11-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_en_order_address_ru_order_city_en_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='order',
            index_together={('id', 'slug')},
        ),
    ]
