# Generated by Django 4.1 on 2022-11-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_address_zh_hans_order_address_ja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_ja',
            new_name='address_zh_hans',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city_ja',
            new_name='city_zh_hans',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name_ja',
            new_name='first_name_zh_hans',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name_ja',
            new_name='last_name_zh_hans',
        ),
    ]
