# Generated by Django 4.1 on 2022-11-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_address_ja_order_address_zh_hans_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='order',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
