# Generated by Django 4.1 on 2022-11-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_index_together_remove_orderitem_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name_zh_hans',
        ),
    ]
