# Generated by Django 4.1 on 2022-11-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_address_zh_hans_order_city_zh_hans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name_zh_hans',
        ),
    ]
